### ISSUE TITLE
error wrong java version

### ISSUE THREAD

**Issue by GravityRZ** [aptalca/docker-ha-bridge#21]
trying to install this on  a synology runnig dsm 6.2.2
the container available on docker does not seem to be compiled properly.

DSM version is the latest
i installed latest java 211 but it dooes not solve the problem

`Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/bwssystems/HABridge/HABridge has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)`

**Comment by bwssytems** [comment]
Are you using the new ha-bridge-5.3.0RC1?

**Comment by GravityRZ** [comment]
looks like it.
this is in the log
![image](https://user-images.githubusercontent.com/16853535/59442932-71f99300-8dfb-11e9-87d8-d4f410c288c2.png)

**Comment by bwssytems** [comment]
Ahh, yes you are. I changed the ha-bridge release to have two version now for a java 11 and java 8 version so I don't know how the docker container knows which one to pick up when you try to re-install. Try removing your docker setup and try again. Otherwise we I may need to only release a java 8 compatible jar ont he ha-bridge website. Maybe @aptalca could lend a hand?

**Comment by GravityRZ** [comment]
with other docker images you can doubleclick and select the build/version you need.
in this case i can not choose.
please change this so the default version is for java8 and by double clicking i can select the java11 version

**Comment by bwssytems** [comment]
I updated the ha-bridge-5.3.0RC2.jar to be compatible. Try again with the newer version

**Comment by GravityRZ** [comment]
looking good.
installed it from the commandline and i can access the user interface.

here is the log in case you need it.

`2019-06-13 16:19:17,479 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge startup sequence...
2019-06-13 16:19:17,715 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from system properties
2019-06-13 16:19:17,741 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v5.3.0RC2) initializing....
2019-06-13 16:19:17,766 [main] INFO  spark.staticfiles.StaticFilesConfiguration - StaticResourceHandler configured with folder = /public
2019-06-13 16:19:17,800 [main] INFO  com.bwssystems.HABridge.SystemControl - System control service started....
2019-06-13 16:19:17.919:INFO::Thread-0: Logging initialized @1597ms to org.eclipse.jetty.util.log.StdErrLog
2019-06-13 16:19:17,984 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - Initializing UDP response Socket...
2019-06-13 16:19:17,996 [main] INFO  com.bwssystems.HABridge.util.UDPDatagramSender - UDP response Socket initialized to: 50000
2019-06-13 16:19:18,003 [main] INFO  com.bwssystems.HABridge.plugins.http.HTTPHome - HTTP Home created.
2019-06-13 16:19:18,009 [main] INFO  com.bwssystems.HABridge.plugins.harmony.HarmonyHome - Harmony Home created. No Harmony devices configured.
2019-06-13 16:19:18,012 [main] INFO  com.bwssystems.HABridge.plugins.NestBridge.NestHome - Nest Home created. No Nest configured.
2019-06-13 16:19:18,014 [main] INFO  com.bwssystems.HABridge.plugins.hue.HueHome - Hue passthru Home created. No Hue passtrhu systems configured.
2019-06-13 16:19:18,016 [main] INFO  com.bwssystems.HABridge.plugins.hal.HalHome - HAL Home created. No HAL devices configured.
2019-06-13 16:19:18,018 [main] INFO  com.bwssystems.HABridge.plugins.mqtt.MQTTHome - MQTT Home created. No MQTT Clients configured.
2019-06-13 16:19:18,019 [main] INFO  com.bwssystems.HABridge.plugins.hass.HassHome - HomeAssistant Home created. No HomeAssistants configured.
2019-06-13 16:19:18,021 [main] INFO  com.bwssystems.HABridge.plugins.homewizard.HomeWizardHome - HomeWizard Home created. No HomeWizard gateways configured.
2019-06-13 16:19:18,023 [main] INFO  com.bwssystems.HABridge.plugins.exec.CommandHome - Command Home for system program execution created.
2019-06-13 16:19:18,026 [main] INFO  com.bwssystems.HABridge.plugins.tcp.TCPHome - TCP Home created.
2019-06-13 16:19:18,029 [main] INFO  com.bwssystems.HABridge.plugins.udp.UDPHome - UDP Home created.
2019-06-13 16:19:18,031 [main] INFO  com.bwssystems.HABridge.plugins.vera.VeraHome - Vera Home created. No Veras configured.
2019-06-13 16:19:18,032 [main] INFO  com.bwssystems.HABridge.plugins.fibaro.FibaroHome - Fibaro Home created. No Fibaros configured.
2019-06-13 16:19:18,034 [main] INFO  com.bwssystems.HABridge.plugins.domoticz.DomoticzHome - Domoticz Home created. No Domoticz devices configured.
2019-06-13 16:19:18,036 [main] INFO  com.bwssystems.HABridge.plugins.somfy.SomfyHome - Somfy Home created.  No Somfys configured.
2019-06-13 16:19:18,039 [main] INFO  com.bwssystems.HABridge.plugins.lifx.LifxHome - LifxDevice Home created. No LifxDevices configured.
2019-06-13 16:19:18,041 [main] INFO  com.bwssystems.HABridge.plugins.openhab.OpenHABHome - OpenHAB Home created. No OpenHABs configured.
2019-06-13 16:19:18,043 [main] INFO  com.bwssystems.HABridge.plugins.fhem.FHEMHome - FHEM Home created. No FHEMs configured.
2019-06-13 16:19:18,047 [main] INFO  com.bwssystems.HABridge.plugins.broadlink.BroadlinkHome - Broadlink Home created. No Broadlinks configured.
2019-06-13 16:19:18,047 [Thread-0] INFO  spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...
2019-06-13 16:19:18,048 [Thread-0] INFO  spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:8080
2019-06-13 16:19:18,049 [main] INFO  com.bwssystems.HABridge.plugins.moziot.MozIotHome - Mozilla IOT Home created. No Mozilla IOTs configured.
2019-06-13 16:19:18,052 [main] INFO  com.bwssystems.HABridge.plugins.homegenie.HomeGenieHome - HomeGenie Home created. No HomeGenies configured.
2019-06-13 16:19:18,057 [main] WARN  com.bwssystems.HABridge.dao.DeviceRepository - Error reading the file: data/device.db - Does not exist or is not readable. continuing...
2019-06-13 16:19:18.057:INFO:oejs.Server:Thread-0: jetty-9.4.z-SNAPSHOT, build timestamp: 2017-11-21T21:27:37Z, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
2019-06-13 16:19:18,060 [main] WARN  com.bwssystems.HABridge.dao.GroupRepository - Error reading the file: data/group.db - Does not exist or is not readable. continuing...
2019-06-13 16:19:18,060 [main] INFO  com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started.... 
2019-06-13 16:19:18,117 [main] INFO  com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
2019-06-13 16:19:18.156:INFO:oejs.session:Thread-0: DefaultSessionIdManager workerName=node0
2019-06-13 16:19:18.156:INFO:oejs.session:Thread-0: No SessionScavenger set, using defaults
2019-06-13 16:19:18.164:INFO:oejs.session:Thread-0: Scavenging every 660000ms
2019-06-13 16:19:18.218:INFO:oejs.AbstractConnector:Thread-0: Started ServerConnector@48dca993{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-06-13 16:19:18.220:INFO:oejs.Server:Thread-0: Started @1901ms
2019-06-13 16:19:18,222 [main] INFO  com.bwssystems.HABridge.upnp.UpnpSettingsResource - Description xml service started....
2019-06-13 16:19:18,231 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener starting....
2019-06-13 16:19:18,232 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener running and ready....
2019-06-13 16:20:28,505 [qtp1964451250-18] WARN  com.bwssystems.HABridge.util.BackupHandler - Issue getting directory listing for backups in directory: data`

**Comment by bwssytems** [comment]
Looks like you are good now.

**Comment by GravityRZ** [comment]
ok thanks. closing up

now the hard part, getting this to work with domoticz on port 80
